sudo: false

matrix:
  fast_finish: true
  include:
    - python: "3.7"
      env: TOXENV=flake8
    - python: "3.7"
      env: TOXENV=pylint
    - python: "3.7"
      env: TOXENV=pydocstyle
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
#    - python: "nightly"
#      env: TOXENV=py36

cache:
  directories:
    - $HOME/.cache/pip
language: python
script: travis_wait tox
after_success: coveralls

install:
  - sudo apt-get update -q 
  - sudo apt-get install python-dev libpython-dev
  - pip install -r requirements/testing.txt 

after_success: coveralls
